### ISSUE TITLE
Bug: index.html absent.

### ISSUE THREAD

**Issue by 0wwafa** [mounta11n/plusplus-camall#13] opened 2024-05-30 14:33 UTC
### What happened?

Click on NEW UI.
Then from the dropdown menu select old ui.
The url becomes /index.html (which does not exist) while it should become just /

### Name and Version

any

### Relevant log output

```shell
self explainatory. 404. error
```

**Comment by mounta11n** [comment] 2024-05-31 19:07
Thanks for reporting. I have fixed that with [d9742fb](https://github.com/ggerganov/llama.cpp/pull/7633/commits/d9742fbf4efd80e6bb462bf487fc90df3eb3e24c)

I would love if you could confirm that it works now

**Comment by mounta11n** [comment] 2024-06-02 13:05
I'm closing this issue because other users have confirmed it works now

**Closed by mounta11n** 2024-06-02 13:05 UTC
Labels: bug

**Comment by 0wwafa** [comment] 2024-06-26 01:08
Yep. it does.
